### ISSUE TITLE
Concerning outputs from running multiple chains

### ISSUE THREAD

**Issue by chimaerase** [jellis18/PTMCMCSampler#23]
Thanks so much for your work on this library!

I'm seeing some concerning outputs for running more than one chain via `mpirun` as suggested in the README.md.   My code executes with no errors and produces the expected output when I run it synchronously in Python or with one chain via `mpirun`, but I see cryptic error output, and one of the output files is empty when I run exactly the same code with two chains.

To eliminate my code as a source of error, I built an example [repo](https://github.com/chimaerase/PTMCMCExample) that repackages code from PTMCMCSampler's own `simple.ipynb` example in a simple Python script so I can run it via `mpirun`.  The same problem seems to exist when I run the example code.  I've also run some tests of my environment that seem to indicate PCMCMCSampler's dependencies are installed and working.

### Run the example synchronously (1 chain):
Outputs are descriptive and imply success.

```bash
$ python gaussian_example.py /code/output
Running chain 1 of 1
Chain 1: Starting sampler.sample()
Adding DE jump with weight 20
Finished 99.00 percent in 36.519649 s Acceptance rate = 0.310657
Run Complete
Chain 1 of 1: done in 36.92 s
```

### Re-run the example code using 2 chains:
Note the cryptic read error messages at the end of many lines of output.

```bash
$ mpirun -n 2 python /code/gaussian_example.py /code/output
Running chain 2 of 2
Running chain 1 of 2
Chain 2: Starting sampler.sample()
Chain 1: Starting sampler.sample()
[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
Adding DE jump with weight 20
Finished 1.00 percent in 0.386084 s Acceptance rate = 0.387[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
Finished 2.00 percent in 0.806926 s Acceptance rate = 0.324[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
Finished 3.00 percent in 1.230904 s Acceptance rate = 0.304667[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
Finished 4.00 percent in 1.646351 s Acceptance rate = 0.3095[3aab602af2ce:00038] Read -1, expected 80138, errno = 1
... (many more similar errors) ...
Run Complete
Chain 1 of 2: done in 45.23 s
Chain 2 of 2: done in 45.23 s
```

List output files: note that one resulting `chain_*` file (`chain_1.316227766016838.txt` in this example) is empty.

```bash
$ ls -l output/
total 52140
-rw-r--r-- 1 mpiuser mpiuser      198 Oct  4 23:23 DEJump_jump.txt
-rw-r--r-- 1 mpiuser mpiuser 53359822 Oct  4 23:23 chain_1.0.txt
-rw-r--r-- 1 mpiuser mpiuser        0 Oct  4 23:23 chain_1.316227766016838.txt
-rw-r--r-- 1 mpiuser mpiuser     3328 Oct  4 23:23 cov.npy
-rw-r--r-- 1 mpiuser mpiuser     1098 Oct  4 23:23 covarianceJumpProposalAM_jump.txt
-rw-r--r-- 1 mpiuser mpiuser     1103 Oct  4 23:23 covarianceJumpProposalSCAM_jump.txt
-rw-r--r-- 1 mpiuser mpiuser     1121 Oct  4 23:23 jump_jump.txt
-rw-r--r-- 1 mpiuser mpiuser       85 Oct  4 23:23 jumps.txt
```

### Runtime environment

I've been testing in a Docker container so that my code executes in a controlled / repeatable runtime environment.  It's possible that the problem is in that environment, but my tests (e.g. of `mpi4py`) seem to indicate that's not the case.  Whether or not the problem is ultimately in my environment, I'm also hoping that with some simple changes to this example Docker image, it could potentially save others in the community a great deal of time in setting up a runtime environment for using PTMCMCSampler.

Run some examples shipped with `mpi4py`:
```bash
$ mpirun -n 5 python -m mpi4py.bench helloworld
Hello, World! I am process 0 of 5 on 12cbf9dbaed5.
Hello, World! I am process 2 of 5 on 12cbf9dbaed5.
Hello, World! I am process 1 of 5 on 12cbf9dbaed5.
Hello, World! I am process 3 of 5 on 12cbf9dbaed5.
Hello, World! I am process 4 of 5 on 12cbf9dbaed5.
 
# pass a message around a ring of MPI processes for 10 loops
$ mpirun -n 6 python -m mpi4py.bench ringtest --loop 10
time for 10 loops = 0.0007474 seconds (6 processes, 1 bytes)
```

**Comment by jellis18** [comment]
@chimaerase I'm looking into this. I can't reproduce it locally or in an ubuntu container. It may be a buster issue https://forums.docker.com/t/many-complaints-during-mpi-within-container/92554. I was able to reproduce using the buster image. 'll keep looking into it though

**Comment by chimaerase** [comment]
Closing this ticket since I've been able to prove that this is not a bug in `PTMCMCSampler`.  After digging a bit deeper into the dependencies, I found [this ticket](https://github.com/open-mpi/ompi/issues/4948), which included a fix that worked to resolve the problem in my example Docker container.   It appears this is an interaction between Docker's defaults and MPI's needs.  This specific bug report is from `openmpi`, though the same problem occurred using `mpich` in Docker.

The fix I that worked in my example container was to add a parameter to the Docker run command.  Then a run of multiple chains no longer had the cryptic error messages.  One of the output files was still empty, but this no longer appears to be a result of the same issue.

Hopefully this Docker container may be useful to help prevent others from having the same issue.  If you're interested in including it in PTMCMCSampler, I'm happy to file a PR for that.

```
$ docker run -it --rm --cap-add=SYS_PTRACE ptmcmc-example
mpiuser@a2336074ce13:/code$ mpirun -n 2 python /code/gaussian_example.py /code/output
Running chain 1 of 2
Running chain 2 of 2
Chain 1: Starting sampler.sample()
Chain 2: Starting sampler.sample()
Adding DE jump with weight 20
Finished 99.00 percent in 51.989734 s Acceptance rate = 0.00757576
Run Complete
Chain 1 of 2: done in 52.48 s
Chain 2 of 2: done in 52.48 s
mpiuser@a2336074ce13:/code$ ls -l output/
total 52084
-rw-r--r-- 1 mpiuser mpiuser      979 Nov  2 23:41 DEJump_jump.txt
-rw-r--r-- 1 mpiuser mpiuser 53306710 Nov  2 23:41 chain_1.0.txt
-rw-r--r-- 1 mpiuser mpiuser        0 Nov  2 23:40 chain_1.316227766016838.txt
-rw-r--r-- 1 mpiuser mpiuser     3328 Nov  2 23:41 cov.npy
-rw-r--r-- 1 mpiuser mpiuser     1048 Nov  2 23:41 covarianceJumpProposalAM_jump.txt
-rw-r--r-- 1 mpiuser mpiuser      965 Nov  2 23:41 covarianceJumpProposalSCAM_jump.txt
-rw-r--r-- 1 mpiuser mpiuser     1161 Nov  2 23:41 jump_jump.txt
-rw-r--r-- 1 mpiuser mpiuser       85 Nov  2 23:41 jumps.txt
```
