### ISSUE TITLE
Last 1000 samples are almost always discarded

### ISSUE THREAD

**Issue by kdolum** [jellis18/PTMCMCSampler#39]
Suppose you say you want 100,000 samples, and `isave` is the default 1000.  The first sample is the initial sample.  Thus the sampler takes 99,999 steps and finishes.  The initial sample has `iter=0`. The final sample has `iter=99,999`, and since this isn't a multiple of `isave`, it isn't written out.  The last write takes place at `iter=99,000` and writes samples numbered 98,000...98,999.  Samples 99,000...99,999 are never written.

You might think you could work around this by requesting 100,001 samples, but then it crashes because of issue #20.

In my opinion, the right fix is to make `Niter` the number of steps that you are requesting, i.e., the number of samples not including the initial one.  Then the number of samples written out will be `Niter/thin + 1`.  I would write the initial sample immediately, then call `writeToFile` with `iter=1000, 2000, ..., 100,000`, with each call writing the last 100 (i.e., `isave/thin`) samples numbered `iter-isave+10, iter-isave+20, ..., iter`.

**Comment by AaronDJohnson** [comment]
Related to #10

**Comment by kdolum** [comment]
Duplicate of #10.  I moved my comments there.
